### ISSUE TITLE
In CMD GEO script, why are you using arrow notation for method definitions?

### ISSUE THREAD

**Issue by Razpudding** [larsdouweschuitema/minor-web-app-from-scratch#5]
What's the purpose of doing that? I think it's confusing and unecessary but maybe you have a good reason -> discuss.

**Comment by larsdouweschuitema** [comment]
After reading some sources I agree on the fact that shorthand function syntax is more suitable in this case and therefor I replaced the arrow function syntax with the shorthand function syntax.
